[project]
name = "edy"
version = "0.1.0"
dependencies = [
    "opencv-python",
    "numpy",
    "matplotlib",
    "torch",
]

[project.urls]
Repository = "https://github.com/Arktetra/edy.git"

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu130"
default = true

[[tool.uv.index]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
